backend:
  name: github
  repo: shuohui-air-technology/shuohui-pages
  branch: main
  base_url: https://shuohui-cms-oauth.shuohui.workers.dev/
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "math"
    label: "学术与推导笔记"
    folder: "content/math"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "文章标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "是否开启公式(LaTeX)", name: "math", widget: "boolean", default: true }
      - { label: "是否开启评论", name: "comments", widget: "boolean", default: true }
      - { label: "文章内容", name: "body", widget: "markdown" }

  - name: "acg"
    label: "二次元与游戏随笔"
    folder: "content/acg"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "文章标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "封面图片", name: "cover.image", widget: "image", required: false }
      - { label: "是否开启评论", name: "comments", widget: "boolean", default: true }
      - { label: "随笔内容", name: "body", widget: "markdown" }
